name: Preview Cleanup

permissions:
  contents: write

on:
  pull_request_target:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - run: mkdir -p empty_dir

      - name: Url slug variable
        run: |
          echo "URL_SLUG=${{ github.event.pull_request.number }}-${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: empty_dir
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          repository-name: esis-mission/esis-pr-previews
          branch: 'main'
          clean: true
          target-folder: ${{ env.URL_SLUG }}
          commit-message: "Remove preview for PR ${{ env.URL_SLUG }}"
          single-commit: true
          git-config-name: esis-bot
          git-config-email: roytsmart+esis-bot@gmail.com
